/*
 * This file was automatically generated by EvoSuite
 * Sun Feb 22 12:43:12 GMT 2026
 */

package br.ufjf.ia;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import br.ufjf.ia.FinanceCalculator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FinanceCalculator_ESTest extends FinanceCalculator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      int int0 = financeCalculator0.paybackPeriods(311.4, 311.4);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      int int0 = financeCalculator0.paybackPeriods(1.0, (-1194.3383));
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      int int0 = financeCalculator0.paybackPeriods((-1.0), (-1.0));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      // Undeclared exception!
      try { 
        financeCalculator0.presentValue((-1615.4), (-1615.4), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // rate must be > -1.0
         //
         verifyException("br.ufjf.ia.FinanceCalculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      // Undeclared exception!
      try { 
        financeCalculator0.presentValue(0.0, (-1.0), (-5621));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // periods must be >= 0
         //
         verifyException("br.ufjf.ia.FinanceCalculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      double double0 = financeCalculator0.presentValue((-1.0), 0.0, 2955);
      assertEquals((-1.0), double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      double double0 = financeCalculator0.futureValue(3586.83422182023, 3586.83422182023, 1431655765);
      assertEquals(Double.POSITIVE_INFINITY, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      // Undeclared exception!
      try { 
        financeCalculator0.compoundInterest(0.0, 0.0, (-1085));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // periods must be >= 0
         //
         verifyException("br.ufjf.ia.FinanceCalculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      // Undeclared exception!
      try { 
        financeCalculator0.log10(0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // log10 domain error
         //
         verifyException("br.ufjf.ia.FinanceCalculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      double double0 = financeCalculator0.log10(3586.83422182023);
      assertEquals(3.5547113046903362, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      // Undeclared exception!
      try { 
        financeCalculator0.ln((-1020.3182080318));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // ln domain error
         //
         verifyException("br.ufjf.ia.FinanceCalculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      double double0 = financeCalculator0.ln(1.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      // Undeclared exception!
      try { 
        financeCalculator0.div(31.065791, 0.0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Division by zero
         //
         verifyException("br.ufjf.ia.FinanceCalculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      double double0 = financeCalculator0.div(1983.5973797, 1983.5973797);
      assertEquals(1.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      // Undeclared exception!
      try { 
        financeCalculator0.compoundInterest((-1.0), (-495.2655678), 0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // rate must be >= -1.0
         //
         verifyException("br.ufjf.ia.FinanceCalculator", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      double double0 = financeCalculator0.sub(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      double double0 = financeCalculator0.mul(1.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      FinanceCalculator financeCalculator0 = new FinanceCalculator();
      double double0 = financeCalculator0.add(0.0, 0.0);
      assertEquals(0.0, double0, 0.01);
  }
}
